# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whstock',
            name='hid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='whstock',
            name='num',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='whstock',
            name='pid',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='whstock',
            name='wid',
            field=models.BigIntegerField(default=-1),
        ),
    ]
