# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20170426_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whstock',
            old_name='num',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='whstock',
            old_name='wid',
            new_name='whnum',
        ),
    ]
