# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_auto_20170427_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ship_id',
            field=models.IntegerField(default=-1),
        ),
    ]
