# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_transaction_ship_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='package_id',
            field=models.IntegerField(default=-1),
        ),
    ]
