# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_auto_20170428_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='whstock',
            name='ctlg_id',
            field=models.IntegerField(default=-1),
        ),
    ]
