# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_whstock_ctlg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whstock',
            name='href',
            field=models.CharField(default='', max_length=500),
        ),
    ]
