# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_whstock_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address_x',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='address_y',
            field=models.IntegerField(default=-1),
        ),
    ]
